import styles from './Skill.module.css'
import Image from 'next/image'

export default function Skills(){
    return(
        <div className={styles.skills} id='skills'>
            <h1>Skills</h1>
            <p>Meus conhecimentos técnicos</p>
            <div className={styles.mainContainer}>
                <span>Principais skills:</span>
                <div className={styles.mainSkills}>
                    <ul>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg'
                                alt='next'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg'
                                alt='react'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg'
                                alt='javascript'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg'
                                alt='sass'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg'
                                alt='bootstrap'
                                height={35}
                                width={35}
                            />
                        </li>
                    </ul>
                </div>
                <span>Todas skills:</span>
                <div className={styles.fullSkills}>
                    <ul>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg'                            
                                alt='html'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg'                          
                                alt='css'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-original.svg'
                                alt='jquery'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg'                        
                                alt='python'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original.svg'
                                alt='vue.js'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gulp/gulp-plain.svg'
                                alt='gulp'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg'
                                alt='git'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg'
                                alt='node.js'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg'
                                alt='typescript'
                                height={35}
                                width={35}
                            />
                        </li>
                        <li>
                            <Image
                                src='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg'
                                alt='mysql'
                                height={35}
                                width={35}
                            />
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    )
}